### ISSUE TITLE
Demo available?

### ISSUE THREAD

**Issue by jamielob** [copleykj/socialize-messaging#1]
Hi! Have you put together a demo or example repo for the socialize packages? Thanks!

**Comment by Fabs** [comment]
I agree it would be very nice :+1:

**Comment by copleykj** [comment]
I started work on a demo app a couple weeks ago but some other work has taken priority recently. I'm hoping to continue work on the demo in the next couple weeks.

**Comment by jamielob** [comment]
Great! Thanks.

**Comment by voidale** [comment]
+1 looks interesting, good job. Is this messaging are ok to be used or not yet?

**Comment by copleykj** [comment]
Yes, it's ok to be used.. There may be some minor API changes in the near future but nothing breaking.

**Comment by voidale** [comment]
Just wanted to say thanks, It's really awesome set of packages. I really enjoyed going through it and figuring out how it works and learned a lot along the way. I think it was done intelligently, Thanks a lot for sharing.

**Comment by voidale** [comment]
@copleykj is there an effective way to check for an existing conversation between participants? I would like to avoid creating new conversations if here is an existing one.

**Comment by copleykj** [comment]
@voidale Currently there is not, but I'm actually going to need this functionality in an upcoming project so I'll be working out how exactly to accomplish this and I'll see if I can get it into the update with the fix for the publication and time sync issue.

also just so everyone knows, the changes for this will likely involve a database migration for any conversations that already exist.

**Comment by copleykj** [comment]
Ok, I started a simple demo. https://github.com/copleykj/socialize-messaging-demo

It's still lacking a bit of UI, but the code does demonstrate the basic use of the package. Will add more functionality as time allows.

**Comment by jamielob** [comment]
Thanks @copleykj - I'll check it out soon!
