### ISSUE TITLE
Html supprot

### ISSUE THREAD

**Issue by SkywardSolutions** [copleykj/socialize-messaging#15]
Does it support html messages?
I mean if I will enter and start new line and send message.

Does new line will be there?

**Comment by copleykj** [comment]
You've closed this but I'll leave an answer anywya. This does support any kind of HTML out of the box and is just plain text. It can of course be extended quite easily to do just about anything you can imagine. That being said, you don't need to modify it to display the line breaks in the message, you need only to set the `white-space` property of the containing element in css to a value that preserves new lines.
