### ISSUE TITLE
Delete all the messages or conversation

### ISSUE THREAD

**Issue by SkywardSolutions** [copleykj/socialize-messaging#17]
Is there any possibility for delete message or conversation at any user end. If I have a long chat history with userA, and I want to delete the history. But userA can still see the history.

**Comment by copleykj** [comment]
Currently you can delete a conversation. If there are multiple users the conversation will stay active for users that still have not deleted the conversation. When the number of participants in the conversation reaches 1 the conversation becomes read only. Once the final person deletes the conversation it will be fully deleted and all messages will be permanently deleted.

**Comment by copleykj** [comment]
As far as clearing the history this could be easily implemented on top of this package. If this is something you would like to see as part of the package please submit a feature request.
