### ISSUE TITLE
How participant.user().username will work?

### ISSUE THREAD

**Issue by varunajmera0** [copleykj/socialize-messaging#25]
what is prototype ?
participant.user().username how it will work. it is not working. @copleykj

**Comment by StorytellerCZ** [comment]
If it is not working for you, the issue might be in your publish/subscribe. It is a common error, not working because the function does not have the needed data.
Check my package that makes sure that you have all the data on the client: https://atmospherejs.com/storyteller/messaging-server

**Comment by varunajmera0** [comment]
okay thanks @StorytellerCZ . i will try.
