### ISSUE TITLE
How do you sort messages?

### ISSUE THREAD

**Issue by Syirrus** [copleykj/socialize-messaging#28]
I'm trying to return the following:
return conversation.messages();

How can you limit and sort the results by newest messages?

**Comment by copleykj** [comment]
The messages method on a conversation takes 4 optional arguments - limit, skip, sortBy, and sortOrder so if you want to get back the first 20 messages sorted in reverse chronological order it would look like so. 

```javascript
conversation.messages(20, null, 'date', -1);
```

**Comment by Syirrus** [comment]
@copleykj  thank you for explaining this better. It seems to alter my list, however in the wrong order. Maybe I was not explicit enough when I asked the question. I want to get the most recent messages listed from oldest to newest. 

In the image below I'm returning all messages. Everything is ordered correctly.
<img width="635" alt="screen shot 2017-07-29 at 9 36 50 am" src="https://user-images.githubusercontent.com/138841/28743094-95418870-7441-11e7-9bf5-de18c8134d45.png">

In this image I'm returning the last 10 message. Note the time stamp. There are newer messages that aren't being displayed. But the counted messages above are correct.  
<img width="633" alt="screen shot 2017-07-29 at 9 39 18 am" src="https://user-images.githubusercontent.com/138841/28743103-d7972284-7441-11e7-908a-79ab00fa92f7.png">

In essences, I just want the last 10 or 20 newest messages to appear at the bottom of the chat window.

Syirrus

**Comment by copleykj** [comment]
You should just be able to change the sortOrder from -1 to 1

**Comment by Syirrus** [comment]
I tried that (-1) and the following is the result:
<img width="631" alt="screen shot 2017-07-29 at 4 08 58 pm" src="https://user-images.githubusercontent.com/138841/28745419-74b28226-7478-11e7-864c-31a14bdb5232.png">

There are new messages that aren't being displayed from 4 hours ago.

If I show all the messages I get this:
<img width="633" alt="screen shot 2017-07-29 at 4 11 54 pm" src="https://user-images.githubusercontent.com/138841/28745435-bc18c4fe-7478-11e7-97de-cf083d453fe5.png">

Syirrus

**Comment by copleykj** [comment]
What if you pass 0 instead of null?

**Comment by Syirrus** [comment]
Sorry where should I pass 0?

**Comment by copleykj** [comment]
I didn't figure it would but it's only possible thing that I can think of that would cause this.

**Comment by Syirrus** [comment]
For sure, it strange.  It works with the list is in reverse order (-1). The newest items are listed up top (4 hours ago). But but when you do a (1) it takes the oldest items first up until the point of how many you limit for.

**Comment by copleykj** [comment]
If you have some way for me to reproduce this, I can take a look tonight

**Comment by Syirrus** [comment]
@copleykj Thank you for your offer. I will see if I can come up with something. 
I have another question actually. I'm still learning Meteor (green) so please bare with me. I'm completely lost on how to use the Meteor.subscribe('viewingConversation', "fMXAoZPxNQGCGCPZQ"); I provide my the conversationId and put this in my Template.conversation.event where the user is getting the conversationId.  After that have no idea how or where to use this publication. If someone isn't viewing the conversation, I would like to call an event to notify the user that they have a message.

**Comment by copleykj** [comment]
The viewing conversation subscription should be run when the user starts viewing the conversation and be stopped when they are no longer viewing. This can be done manually but I think its best to use a reactive contest like a template level subscription or a meteor data container which will handle starting and stopping the subscription automatically.

When the subscription is started it adds the current session to a list of sessions that the user is viewing the conversation from (in case of multiple tabs or devices) on the participant record for that user and sets its read flag to true. While the list contains one or more sessions the read flag will not be updated to false when new messages get added to the conversation. Once all sessions are removed from the list and a new message arrives, the read field will be set to false. This give you the ability to query the participants collection for all of the current users records which have their read field set to false. You can then use that information to display a unread conversation count. In thinking about this I'll probably include a method on the user class with this package called `unreadConversations` in the coming update to make this very task easier.

**Comment by copleykj** [comment]
I just realized you may have meant more of an active notification like sending the user an email or something of that nature, rather than a passive notification.. For that I would personally use a collection hook on the participants collection that on updates checks to see if the read state is being updated to false and then perform needed actions from there.

**Comment by Syirrus** [comment]
Thank you for the explanation.  There are some gaps in my knowledge about Meteor. I think I know what I might be doing wrong. However, I'm not sure how to remedy things. 

I have a conversation template (Template.conversation) which handles the selecting of users in a chat conversation from a dropdown box. Once that is clicked (Template.conversation.event) I set a Session variable with the conversationId and I load a modal to my  Template.messages. Since the conversationId is in a Session variable, I can pull up conversation information etc. 

Now that I'm in (Template.message) I get the Session var and do a Meteor.conversations.findOne({"_id": Session.get("conversationId")});

I then have access to {{#each messages}} {{/each}} 

Question, since I have no reference to {{messages}} (I'm unaware how to access) how can I sort this. When we spoke before I created a helper with the function name {{messageList}} and applied the conversation.messages(); function. Does this make sense?

**Comment by copleykj** [comment]
Its been quite some time since I've used Blaze so some specifics are a little fuzzy, but your best bet is to use your router instead of session to keep track of the conversationId, you can then either use the router to get a reference to the current conversation and add it to the current data context or do as you are doing now and get the conversation id from the router in your page level template and use it to find the conversation and pass it to children templates.
