### ISSUE TITLE
How can I add additional fields to Conversation document?

### ISSUE THREAD

**Issue by vadym-vorobel** [copleykj/socialize-messaging#29]
Hi, @copleykj. Can I add a new field (e.g. `conversationName`) to conversation document?

**Comment by copleykj** [comment]
You can use the appendSchema method provided by BaseModel. Since Conversation extends BaseModel you can call it like so:

```javascript
Conversation.appendSchema({
    conversationName: {
        type: String
    }
});
```

**Comment by vadym-vorobel** [comment]
@copleykj thanks!
