### ISSUE TITLE
effective way to check for an existing conversation between participants

### ISSUE THREAD

**Issue by copleykj** [copleykj/socialize-messaging#3]
@voidale I'm Moving this to a separate issue from #1. Better to keep that issue thread on the topic of a demo and track this issue separately.

**Comment by voidale** [comment]
@copleykj Hi, any update on this one?

**Comment by copleykj** [comment]
Sorry, been quite busy.. I've got this started, just have to finish it up and release.. Should be able to get it done before tomorrow.

**Comment by copleykj** [comment]
@voidale basically what I have so far is a server method that you can call with the userId of the other user as a parameter and it will find and return the _id of a conversation where the current user and the specified user are the only ones participating in the conversation. Does this meet your needs?

**Comment by voidale** [comment]
@copleykj yeah it sounds good. will it work with multiple users I have conversations with 2+ users. Thank you.

**Comment by copleykj** [comment]
Not yet, but totally possible.. So with this change the call will be as follows:

```javascript
var participants = [user1._id, user2._id]; //Meteor.userId() automatically included

Meteor.call("findExistingConversationWithUsers", participants, function(error, result){
    if(result){
        //do something with the returned conversation Id
    }
});
```

**Comment by copleykj** [comment]
I believe this should be in order now. I'm just working on updating lower level deps before I do a release.

**Comment by copleykj** [comment]
New version is released. Let me know if you have any issues.
