### ISSUE TITLE
Specify userId when sending messages

### ISSUE THREAD

**Issue by geekwilson** [copleykj/socialize-messaging#34]
I am currently implementing a bot to help relay state changes from the app. New messages can only be sent as the currently logged in user, and cannot be modified afterwards.

Would it be possible to set the user that is sending the message?
Thanks for your time.

**Comment by copleykj** [comment]
This should be a relatively simple fix.

**Comment by copleykj** [comment]
published a fix for this, let me know if it fixes your use case.
