### ISSUE TITLE
Publishing is broken?

### ISSUE THREAD

**Issue by geekwilson** [copleykj/socialize-messaging#35]
I cannot get any documents from the server.

I can print out results from`ConversationsCollection` in a `Tracker.autorun()` and observe the changes.
When I `new Conversation().save()` I can see the document get created locally, and then get removed from the results as the local db gets synced with the server.
The conversation does get created in the database.

Any help please?

**Comment by copleykj** [comment]
Have you subscribed to the proper publication?

**Comment by geekwilson** [comment]
No I didn't, but subscribing still didn't work (as an aside subscribing should be included in the readme as I thought the package handled that itself..)

I ended up recreating this package locally and I noticed that `/conversation-model/common/conversation-model.js` has:

```const ConversationsCollection = new Mongo.Collection('socialize:conversations');```

whereas `/conversation-model/server/publications.js` has:

```publishComposite('socialize.conversations', function publishConversations(options = { limit: 10, sort: { createdAt: -1 } }) {```

... so changing `socialize.conversations` to `socialize:conversations` in the publish makes it work.

**Comment by copleykj** [comment]
https://github.com/copleykj/socialize-messaging/blob/master/API.md#data-publications

**Comment by geekwilson** [comment]
Ah my mistake, I didn't see it buried there.
