### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by jschmold** [copleykj/socialize-messaging#36]
Are there any available type definitions? I've spent the last half an hour searching, and am unable to find any.

**Comment by copleykj** [comment]
There are not

**Comment by jschmold** [comment]
If I wrote the typings, would you be interested in merging them?

**Comment by copleykj** [comment]
Would it be just the Messaging package? I think If you could commit to type definitions for all the packages in the set and any documentation that would be necessary to use them, then I would definitely be interested in merging them. Having support limited to a single package in the set would be awkward.

**Comment by jschmold** [comment]
Eventually I'd certainly like to add the typings to the socialize system in general, since I am using them in a project and there aren't any typings for it. If you'd like to collaborate on the typings across the entirety of Socialize, I'd also be interested in that

**Comment by copleykj** [comment]
I think that TypeScript support would be great. I'm not sure how much help I would be as far as collaboration since I have exactly zero experience with TS. That being said I'll try to help where I can.

**Comment by jschmold** [comment]
Typescript is remarkably easy. The JSDoc already guides you in the right direction. The final, emitted JavaScript is no different than going from >ES6 -> ES5, but instead, you have type annotations. You use a colon and say "this is what it is". The only trick part is functions 

```
function Add(a: number, b: number): number {
  return a + b
}
function Wonky(b: string): boolean {
  return "Wonky: " + b
}
// ^ The "signature" to define a type that contains a value of a reference to a function like this is
let MyAddFn: (firNum: number, secNum: number) => number
MyAddFn = Add // Works
MyAddFn = Wonky // Doesn't work
```

https://www.typescriptlang.org/

**Comment by copleykj** [comment]
I'm going to close this for now as time and funding prevents me from committing effort towards either creating type defs or rewriting each package in TS. If anyone has any desire to see this come to fruition, consider sponsoring my work on here or on Patreon.
