### ISSUE TITLE
How to start conversations?

### ISSUE THREAD

**Issue by coniel** [copleykj/socialize-messaging#4]
Hi, I'm having issues starting a new conversation. As I've understood it, to start a new conversation, you call ```conversation = new Conversation().save();``` and then add participants ```conversation.addParticipants([<array of user _ids>]);``` . However, at this stage I get ```insert failed: Access denied```, and only the current user is added to the conversation. Am I supposed to do something else?

**Comment by coniel** [comment]
I found out what the problem is. In [one of your last commits](https://github.com/copleykj/socialize-messaging/commit/391a95e79af4a28e7ed5e6c3c8d6d0a79d7f4085) you added ```!this.isFromTrustedCode``` as a condition to the autoValue of the participants schema. Since the participants are added from the client, that condition is always true and thus the participant is always given the current user's _id, and insertion fails because they are already in the conversation.

**Comment by copleykj** [comment]
Yes, this has been fixed in a recent commit and as soon as I have a spare minute I will push out a new release.

**Comment by coniel** [comment]
Cool, thanks. Also, thanks a lot for all these socialize packages!

**Comment by kaiyes** [comment]
hi, I am successfully using your social:friendship package and was trying to add messaging between them. I already have a one - one chat system but would like to move to social :messaging. I can save a new conversation but can't seem to be able to add a user to it.

`conversation = new Conversation().save();

user=Meteor.users.findOne({username:Router.current().params.username})._id; 

participants = [Meteor.user()._id, user];

conversation.addParticipants(participants);`

in the console, I can see that new conversations have been saved. But it shows only one participant, like this: 

![](https://discourse-cdn.global.ssl.fastly.net/meteor/uploads/default/original/2X/5/5c98011f74d93dff929016075e60c4f33c31314e.png)

so the conversations do exist. all that is left, is to add a participant to it and then route to the room. But when I try to add a participant, it shows this,

![](https://discourse-cdn.global.ssl.fastly.net/meteor/uploads/default/original/2X/3/3fba9a8ad67cc9f70a597208c44f9003e9f21299.png)

any pointers will be helpful, cheers!!

**Comment by kaiyes** [comment]
@coniel how did you get around this problem?

**Comment by copleykj** [comment]
I'll get out a new release within the next hour or so.

**Comment by copleykj** [comment]
This should be fixed in the 0.4.2 release
