### ISSUE TITLE
messagesFor publication missing options default

### ISSUE THREAD

**Issue by ericvrp** [copleykj/socialize-messaging#8]
options = options || {};

missing in function
   Meteor.publish("messagesFor", function(conversationId, options){
in file
   https://github.com/copleykj/socialize-messaging/blob/master/conversation-model/server/publications.js

**Comment by copleykj** [comment]
Thanks. this should be the next package that gets transitioned away from bundling the publications with the package in favor of app specific publications though so this should prove moot in the near future.

**Comment by copleykj** [comment]
Publications removed in next release.
